# Generated by Django 2.2.4 on 2019-08-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=10)),
                ('author_name', models.CharField(max_length=10)),
                ('book_price', models.IntegerField()),
                ('book_quantity', models.IntegerField()),
            ],
        ),
    ]
